secret_key = "django-key"
DEBUG="True"
USE_POSTGRES="True"
POSTGRES_DB="league"
POSTGRES_USER="league"
POSTGRES_PASSWORD="league"
VITE_PROXY_URL="http://backend:8000"
VITE_HOST=1
DJANGO_ALLOWED_HOSTS="localhost,0.0.0.0,127.0.0.1,backend"