# Generated by Django 5.1a1 on 2024-07-20 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UpgradeKit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(max_length=50)),
                ('price_reduction', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='team',
            name='balance',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='team',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='team',
            name='manufacturers',
            field=models.ManyToManyField(related_name='teams', to='sheets.manufacturer'),
        ),
        migrations.CreateModel(
            name='Tank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('battle_rating', models.FloatField()),
                ('price', models.IntegerField()),
                ('manufacturers', models.ManyToManyField(related_name='tanks', to='sheets.manufacturer')),
            ],
        ),
        migrations.CreateModel(
            name='TeamTank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_upgradable', models.BooleanField(default=True)),
                ('tank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sheets.tank')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sheets.team')),
            ],
        ),
        migrations.AddField(
            model_name='team',
            name='tanks',
            field=models.ManyToManyField(related_name='teams', through='sheets.TeamTank', to='sheets.tank'),
        ),
        migrations.CreateModel(
            name='TeamUpgradeKit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sheets.team')),
                ('upgrade_kit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sheets.upgradekit')),
            ],
        ),
        migrations.AddField(
            model_name='team',
            name='upgrade_kits',
            field=models.ManyToManyField(related_name='teams', through='sheets.TeamUpgradeKit', to='sheets.upgradekit'),
        ),
        migrations.CreateModel(
            name='UpgradePath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_tank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upgrade_from', to='sheets.tank')),
                ('to_tank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upgrade_to', to='sheets.tank')),
                ('upgrade_kit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sheets.upgradekit')),
            ],
        ),
        migrations.AddField(
            model_name='tank',
            name='upgrades',
            field=models.ManyToManyField(related_name='downgrades', through='sheets.UpgradePath', to='sheets.tank'),
        ),
    ]
