# Generated by Django 5.1a1 on 2024-07-20 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0002_manufacturer_upgradekit_team_balance_alter_team_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upgradepath',
            name='upgrade_kit',
        ),
        migrations.AddField(
            model_name='upgradepath',
            name='required_kit_tier',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.RemoveField(
            model_name='team',
            name='upgrade_kits',
        ),
        migrations.AddField(
            model_name='team',
            name='upgrade_kits',
            field=models.JSONField(default=dict),
        ),
    ]
