# Generated by Django 5.1a1 on 2024-07-20 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0003_remove_upgradepath_upgrade_kit_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TeamUpgradeKit',
        ),
        migrations.DeleteModel(
            name='UpgradeKit',
        ),
    ]
