# Generated by Django 5.1a1 on 2024-07-20 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0004_delete_teamupgradekit_delete_upgradekit'),
    ]

    operations = [
        migrations.AddField(
            model_name='upgradepath',
            name='cost',
            field=models.IntegerField(default=0),
        ),
    ]
