# Generated by Django 5.1a1 on 2024-07-20 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0005_upgradepath_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='upgrade_kits',
            field=models.JSONField(default={'T1': {'price': 25000, 'quantity': 0}, 'T2': {'price': 50000, 'quantity': 0}, 'T3': {'price': 100000, 'quantity': 0}}),
        ),
    ]
