# Generated by Django 5.1a1 on 2024-07-25 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0006_alter_team_upgrade_kits'),
    ]

    operations = [
        migrations.AddField(
            model_name='tank',
            name='rank',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='tank',
            name='type',
            field=models.CharField(default='MT', max_length=50),
        ),
        migrations.AlterField(
            model_name='tank',
            name='battle_rating',
            field=models.FloatField(default=1.0),
        ),
        migrations.AlterField(
            model_name='tank',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
