# Generated by Django 5.1a1 on 2024-07-28 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0008_match_teammatch_match_teams'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammatch',
            name='side',
            field=models.CharField(choices=[('team_1', 'Team 1'), ('team_2', 'Team 2')], default='team_1', max_length=10),
        ),
    ]
