# Generated by Django 5.1a1 on 2024-07-28 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0010_alter_team_upgrade_kits'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='was_played',
            field=models.BooleanField(default=False),
        ),
    ]
