# Generated by Django 5.1a1 on 2024-07-31 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0011_match_was_played'),
    ]

    operations = [
        migrations.CreateModel(
            name='Judge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sheets.team')),
            ],
        ),
        migrations.CreateModel(
            name='Substitute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.IntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High')])),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sheets.team')),
            ],
        ),
        migrations.CreateModel(
            name='MatchResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winning_side', models.CharField(choices=[('team_1', 'Team 1'), ('team_2', 'Team 2')], max_length=10)),
                ('bonuses', models.TextField(blank=True, null=True)),
                ('penalties', models.TextField(blank=True, null=True)),
                ('tanks_lost', models.JSONField(default=dict)),
                ('judge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sheets.judge')),
                ('match', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='sheets.match')),
                ('substitutes', models.ManyToManyField(related_name='match_results', to='sheets.substitute')),
            ],
        ),
    ]
