# Generated by Django 5.1a1 on 2024-07-31 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0012_judge_substitute_matchresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchresult',
            name='bonuses',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='matchresult',
            name='penalties',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
