# Generated by Django 5.1a1 on 2024-08-09 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0014_alter_matchresult_judge_remove_matchresult_bonuses_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='substitute',
            name='side',
            field=models.CharField(choices=[('team_1', 'Team 1'), ('team_2', 'Team 2')], default='team_1', max_length=10),
        ),
        migrations.AddField(
            model_name='substitute',
            name='team_played_for',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assisted_by_substitutes', to='sheets.team'),
        ),
        migrations.AlterField(
            model_name='substitute',
            name='match_result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substitutes', to='sheets.matchresult'),
        ),
        migrations.AlterField(
            model_name='substitute',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substitute_teams', to='sheets.team'),
        ),
        migrations.AlterField(
            model_name='tanklost',
            name='match_result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tanks_lost', to='sheets.matchresult'),
        ),
    ]
