# Generated by Django 5.1a1 on 2024-08-09 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0015_substitute_side_substitute_team_played_for_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchresult',
            name='is_calced',
            field=models.BooleanField(default=False),
        ),
    ]
