# Generated by Django 5.1a1 on 2024-09-30 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': (('commander_permissions', 'Is a team Commander'), ('judge_permissions', 'Is a judge'), ('admin_permissions', 'Is an admin'))},
        ),
    ]
