# Generated by Django 5.1a1 on 2024-09-30 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0005_alter_team_members'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='members',
        ),
    ]
