# Generated by Django 5.1a1 on 2024-10-06 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0007_alter_tank_manufacturers_teamlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamlog',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tank',
            name='manufacturers',
            field=models.ManyToManyField(blank=True, related_name='tanks', to='sheets.manufacturer'),
        ),
    ]
