# Generated by Django 5.1a1 on 2024-10-06 13:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0008_teamlog_description_alter_tank_manufacturers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teamlog',
            name='change_timestamp',
        ),
        migrations.AddField(
            model_name='teamlog',
            name='method_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teamlog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='teamlog',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='teamlog',
            name='field_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='teamlog',
            name='new_value',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='teamlog',
            name='previous_value',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='teamlog',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sheets.team'),
        ),
    ]
