# Generated by Django 5.1.2 on 2024-11-24 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0011_teamtank_is_trad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='datetime',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='teamlog',
            name='method_name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='teamlog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
