# Generated by Django 5.1.2 on 2024-12-04 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0013_tankbox_is_national_alter_tankbox_tanks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tankbox',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
