# Generated by Django 5.1.2 on 2024-12-14 15:22

import django.db.models.deletion
import sheets.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0014_alter_tankbox_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tankbox',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='ImportTank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount', models.IntegerField()),
                ('available_until', models.DateTimeField(default=sheets.models.default_expiry_date)),
                ('is_purchased', models.BooleanField(default=False)),
                ('tank', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='import_tank', to='sheets.tank')),
            ],
        ),
    ]
