# Generated by Django 5.1.2 on 2024-12-14 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0015_alter_tankbox_id_importtank'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportCriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_rank', models.IntegerField(blank=True, help_text='Minimum rank of tanks to include.', null=True)),
                ('max_rank', models.IntegerField(blank=True, help_text='Maximum rank of tanks to include.', null=True)),
                ('tank_type', models.CharField(blank=True, help_text='Filter by tank type (e.g., MT, HT).', max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Activate this criteria for offer generation.')),
            ],
        ),
    ]
