# Generated by Django 5.1a1 on 2024-08-12 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0016_matchresult_is_calced'),
    ]

    operations = [
        migrations.CreateModel(
            name='TankBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.IntegerField(default=0)),
                ('tanks', models.ManyToManyField(to='sheets.tank')),
            ],
        ),
        migrations.CreateModel(
            name='TeamBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
                ('box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sheets.tankbox')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sheets.team')),
            ],
        ),
        migrations.AddField(
            model_name='team',
            name='tank_boxes',
            field=models.ManyToManyField(related_name='teams', through='sheets.TeamBox', to='sheets.tankbox'),
        ),
    ]
