# Generated by Django 5.1.2 on 2024-12-14 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0016_importcriteria'),
    ]

    operations = [
        migrations.AddField(
            model_name='importcriteria',
            name='required_tank_count',
            field=models.IntegerField(blank=True, default=0, help_text='Minimum number of tanks from the required list to include.', null=True),
        ),
        migrations.AddField(
            model_name='importcriteria',
            name='required_tanks',
            field=models.ManyToManyField(blank=True, help_text='List of specific tanks to always include in offers.', related_name='criteria', to='sheets.tank'),
        ),
    ]
