# Generated by Django 5.1a1 on 2024-08-25 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0017_tankbox_teambox_team_tank_boxes'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='color',
            field=models.CharField(default='#000000', max_length=7),
        ),
    ]
