# Generated by Django 5.1.2 on 2024-12-14 15:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0017_importcriteria_required_tank_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='importtank',
            name='available_from',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 14, 15, 42, 15, 719857, tzinfo=datetime.timezone.utc)),
        ),
    ]
