# Generated by Django 5.1a1 on 2024-09-15 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0018_team_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammatch',
            name='tanks',
        ),
        migrations.CreateModel(
            name='TankAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('tank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sheets.tank')),
                ('team_match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sheets.teammatch')),
            ],
            options={
                'unique_together': {('team_match', 'tank')},
            },
        ),
    ]
