# Generated by Django 5.1a1 on 2024-09-15 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0019_remove_teammatch_tanks_tankassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammatch',
            name='tanks',
            field=models.ManyToManyField(related_name='team_matches', to='sheets.tank'),
        ),
        migrations.DeleteModel(
            name='TankAssignment',
        ),
    ]
