# Generated by Django 5.1a1 on 2024-09-15 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0020_teammatch_tanks_delete_tankassignment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammatch',
            name='tanks',
        ),
        migrations.AddField(
            model_name='teammatch',
            name='team_tanks',
            field=models.ManyToManyField(related_name='team_matches', to='sheets.teamtank'),
        ),
    ]
