# Generated by Django 5.1a1 on 2024-09-15 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0021_remove_teammatch_tanks_teammatch_team_tanks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teammatch',
            old_name='team_tanks',
            new_name='tanks',
        ),
    ]
