# Generated by Django 5.1.2 on 2024-12-17 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0021_importtank_criteria'),
    ]

    operations = [
        migrations.AddField(
            model_name='importcriteria',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
