# Generated by Django 5.1.2 on 2024-12-17 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0022_importcriteria_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importcriteria',
            name='max_rank',
            field=models.IntegerField(blank=True, default=6, help_text='Maximum rank of tanks to include.', null=True),
        ),
        migrations.AlterField(
            model_name='importcriteria',
            name='min_rank',
            field=models.IntegerField(blank=True, default=0, help_text='Minimum rank of tanks to include.', null=True),
        ),
        migrations.AlterField(
            model_name='importtank',
            name='tank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_tanks', to='sheets.tank'),
        ),
    ]
