# Generated by Django 5.1.2 on 2024-12-17 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0023_alter_importcriteria_max_rank_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tankbox',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
