# Generated by Django 5.1.2 on 2024-12-17 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0024_alter_tankbox_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teambox',
            name='amount',
        ),
    ]
