# Generated by Django 5.1.2 on 2024-12-24 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0025_remove_teambox_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='tankbox',
            name='tier',
            field=models.IntegerField(default=1),
        ),
    ]
