# Generated by Django 5.1.2 on 2024-12-24 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0026_tankbox_tier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tankbox',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
