# Generated by Django 5.1.2 on 2025-01-05 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0027_alter_tankbox_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchresult',
            name='round_score',
            field=models.CharField(blank=True, help_text="Enter the score as 'X:Y' (e.g., 2:1)", max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='total_money_earned',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='total_money_spent',
            field=models.IntegerField(default=0),
        ),
    ]
