# Generated by Django 5.1.2 on 2025-01-26 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0028_matchresult_round_score_team_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamresult',
            name='was_present',
            field=models.BooleanField(default=True),
        ),
    ]
