# Generated by Django 5.1.2 on 2025-01-26 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0029_teamresult_was_present'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='webhook_id_schedule',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
