# Generated by Django 5.1.2 on 2025-01-26 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0030_match_webhook_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='discord_role_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
