# Generated by Django 5.1.2 on 2025-01-27 18:47

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0032_match_webhook_id_calc_match_webhook_id_result_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='webhook_id_schedule',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]

