# Generated by Django 5.1.2 on 2025-02-09 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0033_remove_match_webhook_id_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamtank',
            name='from_auctions',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teamtank',
            name='value',
            field=models.IntegerField(default=0),
        ),
    ]
