# Generated by Django 5.1.2 on 2025-03-15 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0034_teamtank_from_auctions_teamtank_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='tank',
            name='is_ghost',
            field=models.BooleanField(default=False),
        ),
    ]
