# Generated by Django 5.1.2 on 2025-03-15 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0035_tank_is_ghost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tank',
            name='is_ghost',
        ),
        migrations.AddField(
            model_name='teamtank',
            name='is_ghost',
            field=models.BooleanField(default=False),
        ),
    ]
