# Generated by Django 5.1.2 on 2025-04-11 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0036_remove_tank_is_ghost_teamtank_is_ghost'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='win_rate',
            field=models.FloatField(default=0),
        ),
    ]
