# Generated by Django 5.1.2 on 2025-05-08 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0037_team_win_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('multiplier', models.FloatField(default=1.0)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('match_limited', models.BooleanField(default=False)),
                ('matches_left', models.IntegerField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='team',
            name='win_rate',
        ),
        migrations.AddField(
            model_name='team',
            name='booster',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team', to='sheets.booster'),
        ),
    ]
