# Generated by Django 5.1.2 on 2025-05-08 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0038_booster_remove_team_win_rate_team_booster'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='booster',
        ),
        migrations.AddField(
            model_name='booster',
            name='name',
            field=models.CharField(default='test', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booster',
            name='team',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booster', to='sheets.team'),
        ),
    ]
