# Generated by Django 5.1.2 on 2025-07-26 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0039_remove_team_booster_booster_name_booster_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamlog',
            name='user',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
