# Generated by Django 5.1.2 on 2025-08-02 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0041_match_channel_id_calc_match_channel_id_result_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='upgradepath',
            name='in_graph',
            field=models.BooleanField(default=False),
        ),
    ]
