# Generated by Django 5.1.2 on 2025-08-09 23:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0042_upgradepath_in_graph'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpgradeTree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TreeTank', to='sheets.tank')),
            ],
        ),
    ]
