# Generated by Django 5.1.2 on 2025-12-18 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0043_upgradetree'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teamtank',
            name='is_ghost',
        ),
        migrations.CreateModel(
            name='Interchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_bidirectional', models.BooleanField(default=True)),
                ('from_tank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interchanges_from', to='sheets.tank')),
                ('to_tank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interchanges_to', to='sheets.tank')),
            ],
        ),
        migrations.CreateModel(
            name='InterchangeGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('root_tank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interchange_group_root', to='sheets.tank')),
            ],
        ),
    ]
