# Generated by Django 5.1.2 on 2025-12-23 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0045_alliance_team_alliance'),
    ]

    operations = [
        migrations.CreateModel(
            name='BountyTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(choices=[(1, '1st Place'), (2, '2nd Place'), (3, '3rd Place'), (4, '4th Place')], unique=True)),
                ('bounty_value', models.IntegerField(default=50000, help_text='The bounty amount assigned to the team at this rank.')),
            ],
            options={
                'verbose_name': 'Monthly Bounty Setting',
                'verbose_name_plural': 'Monthly Bounty Settings',
                'ordering': ['rank'],
            },
        ),
        migrations.AddField(
            model_name='match',
            name='is_bounty',
            field=models.BooleanField(default=False, help_text='If True, this is a Bounty Challenge match.'),
        ),
        migrations.CreateModel(
            name='Bounty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('value', models.IntegerField(default=0, help_text='The money reward for defeating this team.')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bounties', to='sheets.team')),
            ],
        ),
    ]
