# Generated by Django 5.1.2 on 2026-01-03 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0046_bountytier_match_is_bounty_bounty'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchresult',
            name='judge_is_test',
            field=models.BooleanField(default=False),
        ),
    ]
