# Generated by Django 5.1.2 on 2026-02-22 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0047_matchresult_judge_is_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchRewardRates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('even_split_kill_reward', models.FloatField(default=0.0)),
                ('even_split_repair_cost', models.FloatField(default=0.0)),
                ('money_rule_kill_reward', models.FloatField(default=0.0)),
                ('money_rule_repair_cost', models.FloatField(default=0.0)),
                ('no_rule_kill_reward', models.FloatField(default=0.0)),
                ('no_rule_repair_cost', models.FloatField(default=0.0)),
            ],
        ),
    ]
