# Generated by Django 5.1.2 on 2026-06-14 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0048_matchrewardrates'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='matchrewardrates',
            options={'verbose_name': 'Match Reward Rate', 'verbose_name_plural': 'Match Reward Rates'},
        ),
        migrations.AddField(
            model_name='tank',
            name='internal_ids',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
