# Generated by Django 5.1.2 on 2026-06-14 23:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0049_alter_matchrewardrates_options_tank_internal_ids'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.IntegerField(help_text='Round 1, 2, 3, etc.')),
                ('parsed_files', models.JSONField(default=list)),
                ('map_name', models.CharField(blank=True, max_length=255, null=True)),
                ('parsed_at', models.DateTimeField(auto_now=True)),
                ('is_verified', models.BooleanField(default=False, help_text='True when judge approves the parsed data.')),
                ('team_rosters', models.JSONField(default=dict)),
                ('player_spawns', models.JSONField(default=dict)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parsed_rounds', to='sheets.match')),
            ],
            options={
                'unique_together': {('match', 'round_number')},
            },
        ),
        migrations.CreateModel(
            name='ReplayFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='replays/%Y/%m/%d/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('match_round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replay_files', to='sheets.matchround')),
            ],
        ),
        migrations.CreateModel(
            name='MatchKill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_s', models.FloatField()),
                ('attacker', models.CharField(max_length=100)),
                ('attacker_veh', models.CharField(max_length=100)),
                ('weapon', models.CharField(max_length=100)),
                ('victim', models.CharField(max_length=100)),
                ('victim_veh', models.CharField(max_length=100)),
                ('match_round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kills', to='sheets.matchround')),
            ],
            options={
                'unique_together': {('match_round', 'time_s', 'attacker', 'victim')},
            },
        ),
        migrations.CreateModel(
            name='PlayerTelemetry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=100)),
                ('vehicle_name', models.CharField(max_length=100)),
                ('time_ms', models.IntegerField()),
                ('x', models.FloatField()),
                ('z', models.FloatField()),
                ('match_round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telemetry', to='sheets.matchround')),
            ],
            options={
                'indexes': [models.Index(fields=['match_round', 'player_name'], name='sheets_play_match_r_d63a28_idx')],
                'unique_together': {('match_round', 'player_name', 'time_ms')},
            },
        ),
    ]
