# Generated by Django 5.1.2 on 2026-06-15 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0050_matchround_replayfile_matchkill_playertelemetry'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchround',
            name='telemetry_data',
            field=models.JSONField(default=dict),
        ),
        migrations.DeleteModel(
            name='PlayerTelemetry',
        ),
    ]
