# Generated by Django 5.1.2 on 2026-06-15 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0051_matchround_telemetry_data_delete_playertelemetry'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchround',
            name='win_reason',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='matchround',
            name='winning_team',
            field=models.CharField(blank=True, choices=[('team_1', 'Team 1'), ('team_2', 'Team 2')], max_length=10, null=True),
        ),
    ]
