# Generated by Django 5.1.2 on 2026-06-16 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0052_matchround_win_reason_matchround_winning_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchround',
            name='start_time_s',
            field=models.IntegerField(default=300, help_text='Start time in seconds'),
        ),
    ]
