# Generated by Django 5.1.2 on 2026-06-16 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0053_matchround_start_time_s'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchround',
            name='end_time_s',
            field=models.IntegerField(default=0, help_text='End time in seconds'),
        ),
        migrations.AlterField(
            model_name='matchround',
            name='winning_team',
            field=models.CharField(blank=True, choices=[('team_1', 'Team 1'), ('team_2', 'Team 2'), ('draw', 'Draw')], max_length=10, null=True),
        ),
    ]
