# Generated by Django 5.1.2 on 2026-06-16 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0054_matchround_end_time_s_alter_matchround_winning_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchround',
            name='map_details',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
