# Generated by Django 5.1.2 on 2026-06-18 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0055_matchround_map_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchround',
            name='capture_zones',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='matchround',
            name='map_areas',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
