# Generated by Django 5.1.2 on 2026-06-18 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0056_matchround_capture_zones_matchround_map_areas'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchround',
            name='chat_log',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='matchround',
            name='critical_damage_events',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
