# Generated by Django 5.1.2 on 2026-06-18 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0057_matchround_chat_log_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchCrit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_s', models.FloatField()),
                ('attacker', models.CharField(max_length=100)),
                ('attacker_veh', models.CharField(max_length=100)),
                ('victim', models.CharField(max_length=100)),
                ('victim_veh', models.CharField(max_length=100)),
                ('is_fire', models.BooleanField(default=False)),
                ('match_round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crits', to='sheets.matchround')),
            ],
            options={
                'indexes': [models.Index(fields=['match_round', 'time_s'], name='sheets_matc_match_r_16c1f0_idx')],
            },
        ),
    ]
