# Generated by Django 5.1.2 on 2026-06-19 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0058_matchcrit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchround',
            name='critical_damage_events',
        ),
    ]
