# Generated by Django 5.1.2 on 2026-07-28 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0059_remove_matchround_critical_damage_events'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyEconomySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_matches_for_cap', models.FloatField(default=3.5, help_text='Target matches per week used to compute the cap (e.g., 3.5 = midpoint of 3-4 games).')),
                ('max_weekly_matches', models.IntegerField(default=6, help_text='Maximum matches a team is allowed to play per week.')),
                ('current_cap', models.IntegerField(default=350000, help_text='The dynamic weekly soft cap (auto-calculated).')),
                ('fallback_match_reward', models.IntegerField(default=100000, help_text='Default reward per match if no past match data exists.')),
                ('under_cap_payout_ratio', models.FloatField(default=0.5, help_text='Percentage of under-cap deficit paid out at week end (0.5 = 50%).')),
                ('over_cap_penalty_scaling', models.FloatField(default=1.0, help_text='Scaling multiplier for over-cap penalty.')),
                ('min_reward_floor', models.FloatField(default=0.1, help_text='Minimum reward multiplier floor (0.1 = 10%).')),
                ('ema_weight', models.FloatField(default=0.3, help_text="Weight of the new week's average (0.0 to 1.0). 0.3 means 30% new week, 70% old cap.")),
            ],
            options={
                'verbose_name': 'Weekly Economy Setting',
                'verbose_name_plural': 'Weekly Economy Settings',
            },
        ),
        migrations.AlterField(
            model_name='matchcrit',
            name='attacker',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='matchcrit',
            name='attacker_veh',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='matchcrit',
            name='victim',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='matchcrit',
            name='victim_veh',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='matchkill',
            name='attacker',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='matchkill',
            name='attacker_veh',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='matchkill',
            name='victim',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='matchkill',
            name='victim_veh',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='matchkill',
            name='weapon',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
