# Generated by Django 5.1.2 on 2026-08-07 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0060_weeklyeconomysettings_alter_matchcrit_attacker_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='importtank',
            name='purchased_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchased_imports', to='sheets.team'),
        ),
    ]
