# Generated by Django 5.1.2 on 2026-08-31 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0061_importtank_purchased_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchrewardrates',
            name='advanced_even_split_kill_reward',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='matchrewardrates',
            name='advanced_even_split_repair_cost',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='matchrewardrates',
            name='advanced_money_rule_kill_reward',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='matchrewardrates',
            name='advanced_money_rule_repair_cost',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='matchrewardrates',
            name='advanced_no_rule_kill_reward',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='matchrewardrates',
            name='advanced_no_rule_repair_cost',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='matchrewardrates',
            name='evolved_even_split_kill_reward',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='matchrewardrates',
            name='evolved_even_split_repair_cost',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='matchrewardrates',
            name='evolved_money_rule_kill_reward',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='matchrewardrates',
            name='evolved_money_rule_repair_cost',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='matchrewardrates',
            name='evolved_no_rule_kill_reward',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='matchrewardrates',
            name='evolved_no_rule_repair_cost',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='tank',
            name='advanced_battle_rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='tank',
            name='advanced_value',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tank',
            name='evolved_battle_rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='tank',
            name='is_allowed_in_advanced',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tank',
            name='is_allowed_in_evolved',
            field=models.BooleanField(default=True),
        ),
    ]
