# Generated by Django 5.1.2 on 2026-08-31 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0062_matchrewardrates_advanced_even_split_kill_reward_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='substitute',
            name='bonuses',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='substitute',
            name='penalties',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
