# Generated by Django 5.1.2 on 2026-09-06 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0063_substitute_bonuses_substitute_penalties'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuctionCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_quantity', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tank', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='auction_candidates', to='sheets.tank')),
            ],
            options={
                'ordering': ['tank__name'],
            },
        ),
        migrations.CreateModel(
            name='AuctionCandidateSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='sheets.auctioncandidate')),
                ('source_import', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='auction_source', to='sheets.importtank')),
            ],
            options={
                'ordering': ['source_import__available_from', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AuctionCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('collecting', 'Collecting'), ('voting', 'Voting'), ('scheduled', 'Scheduled'), ('live', 'Live'), ('finished', 'Finished'), ('cancelled', 'Cancelled')], db_index=True, default='collecting', max_length=20)),
                ('batch_target', models.PositiveIntegerField(default=8)),
                ('max_votes_per_team', models.PositiveIntegerField(default=5)),
                ('lot_count', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('minimum_increment', models.PositiveIntegerField(default=1000)),
                ('voting_starts_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('voting_ends_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('auction_starts_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('auction_ends_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'auction_starts_at'], name='sheets_auct_status_7ce5e9_idx'), models.Index(fields=['status', 'voting_ends_at'], name='sheets_auct_status_ef8cd3_idx')],
            },
        ),
        migrations.AddField(
            model_name='auctioncandidate',
            name='cycle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='sheets.auctioncycle'),
        ),
        migrations.CreateModel(
            name='AuctionImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_from', models.DateTimeField(db_index=True, unique=True)),
                ('expired_at', models.DateTimeField()),
                ('total_imports', models.PositiveIntegerField(default=0)),
                ('leftover_imports', models.PositiveIntegerField(default=0)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_batches', to='sheets.auctioncycle')),
            ],
            options={
                'ordering': ['available_from'],
            },
        ),
        migrations.CreateModel(
            name='AuctionLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=0)),
                ('starting_bid', models.PositiveIntegerField()),
                ('minimum_increment', models.PositiveIntegerField(default=1000)),
                ('current_bid', models.PositiveIntegerField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(db_index=True)),
                ('last_bid_at', models.DateTimeField(blank=True, null=True)),
                ('winning_bid', models.PositiveIntegerField(blank=True, null=True)),
                ('finalized_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lots', to='sheets.auctioncandidate')),
                ('current_bidder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leading_auction_lots', to='sheets.team')),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lots', to='sheets.auctioncycle')),
                ('source', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='lot', to='sheets.auctioncandidatesource')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_auction_lots', to='sheets.team')),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AuctionBid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auction_bids', to='sheets.team')),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='sheets.auctionlot')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuctionVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('user', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='sheets.auctioncandidate')),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='sheets.auctioncycle')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auction_votes', to='sheets.team')),
            ],
        ),
        migrations.AddConstraint(
            model_name='auctioncandidate',
            constraint=models.UniqueConstraint(fields=('cycle', 'tank'), name='unique_auction_candidate_tank_per_cycle'),
        ),
        migrations.AddIndex(
            model_name='auctionlot',
            index=models.Index(fields=['cycle', 'position'], name='sheets_auct_cycle_i_5d1ab6_idx'),
        ),
        migrations.AddIndex(
            model_name='auctionlot',
            index=models.Index(fields=['ends_at', 'finalized_at'], name='sheets_auct_ends_at_7930db_idx'),
        ),
        migrations.AddConstraint(
            model_name='auctionlot',
            constraint=models.UniqueConstraint(fields=('cycle', 'position'), name='unique_auction_lot_position'),
        ),
        migrations.AddIndex(
            model_name='auctionbid',
            index=models.Index(fields=['lot', '-created_at'], name='sheets_auct_lot_id_398d30_idx'),
        ),
        migrations.AddIndex(
            model_name='auctionbid',
            index=models.Index(fields=['team', '-created_at'], name='sheets_auct_team_id_1281f7_idx'),
        ),
        migrations.AddIndex(
            model_name='auctionvote',
            index=models.Index(fields=['cycle', 'team'], name='sheets_auct_cycle_i_fb7a59_idx'),
        ),
        migrations.AddIndex(
            model_name='auctionvote',
            index=models.Index(fields=['candidate'], name='sheets_auct_candida_a9dc8b_idx'),
        ),
        migrations.AddConstraint(
            model_name='auctionvote',
            constraint=models.UniqueConstraint(fields=('cycle', 'team', 'candidate'), name='unique_auction_vote_allocation'),
        ),
    ]
