# Generated by Django 5.1.2 on 2026-09-06 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0064_auctioncandidate_auctioncandidatesource_auctioncycle_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuctionIgnoredImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_from', models.DateTimeField(db_index=True, unique=True)),
                ('reason', models.CharField(default='Ignored during auction bootstrap', max_length=255)),
                ('ignored_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
