# Generated by Django 5.1.2 on 2026-09-06 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0065_auctionignoredimportbatch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctioncycle',
            name='lot_count',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='auctioncycle',
            name='minimum_increment',
            field=models.PositiveIntegerField(default=2000),
        ),
        migrations.AlterField(
            model_name='auctionlot',
            name='minimum_increment',
            field=models.PositiveIntegerField(default=2000),
        ),
    ]
