# Generated by Django 5.1.2 on 2026-09-20 11:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0066_alter_auctioncycle_lot_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklyeconomysettings',
            name='fallback_match_reward',
            field=models.IntegerField(default=100000, help_text='Default winning-team reward when no eligible Advanced/Evolved payouts exist in the last 7 days.'),
        ),
        migrations.AddField(
            model_name='weeklyeconomysettings',
            name='active_team_window_days',
            field=models.PositiveIntegerField(default=28, help_text='A team is active if it played any match in this many days.', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='weeklyeconomysettings',
            name='progression_max_multiplier',
            field=models.FloatField(default=1.5, help_text='Upper bound on the season progression multiplier.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)]),
        ),
        migrations.AddField(
            model_name='weeklyeconomysettings',
            name='progression_per_rank',
            field=models.FloatField(default=0.1, help_text='Extra cap multiplier per average rank above the reference (0.1 = +10% per rank). Set 0 to disable.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='weeklyeconomysettings',
            name='progression_reference_rank',
            field=models.FloatField(default=1.0, help_text='Average owned rank at which the progression multiplier is 1.0.', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='weeklyeconomysettings',
            name='reward_trim_fraction',
            field=models.FloatField(default=0.1, help_text='Fraction removed from each end of winning payouts (0.1 = 10% lowest and 10% highest). Rounded down per tail.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(0.45)]),
        ),
    ]
