# Generated by Django 5.1.2 on 2026-09-20 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheets', '0067_weekly_cap_victories_and_progression'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctioncycle',
            name='auction_reminder_announced_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='auctioncycle',
            name='discord_retry_after',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='auctioncycle',
            name='voting_closed_announced_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='auctioncycle',
            name='voting_open_announced_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
